Project/urls.py
""" modulo de URLS general del proyecto """
#bibliografia ----------------------------------------------------
# https://github.com/django/django
# https://docs.djangoproject.com/en/4.0
#importaciones ---------------------------------------------------
#django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
#Views
from posts import views as posts_views
from users import views as users_views

#urls ---------------------------------------------------------------------------
urlpatterns = [
    #url para acceder a admin: ejem: http://127.0.0.1:8000/admin/
    path("admin/", admin.site.urls),#user:administrador; pass:Quieroentrar-77
    #urls apps -------------------------
    path('', include(('posts.urls', 'posts'), namespace='posts')),#include para incluir la lista de urls de post
    path('users/', include(('users.urls', 'users'), namespace='users')),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#archivos estáticos, le suma una url 

posts/urls.py
""" Post de URLS """
#code ---------------------------------------------------------------------------
# Django
from django.urls import path, include
# Views
from posts import views

#urls ---------------------------------------------------------------------------
urlpatterns = [
    #urls apps -------------------------
    path(route='', view=views.PostsFeedView.as_view(), name='feed'),
    path(route='posts/new/', view=views.CreatePostView.as_view(), name='create'),
    path(route='posts/<int:pk>/', view=views.PostDetailView.as_view(), name='detail') 
]

users/urls.py
"""Users URLs"""
# importaciones ------------------------------------------------------
# Django
from django.urls import path
# View
from users import views

# urls -------------------------------------------------------------------
urlpatterns = [
    # Management
    path(route='login/',view=views.LoginView.as_view(),name='login'),
    path(route='logout/',view=views.LogoutView.as_view(),name='logout'),
    path(route='signup/',view=views.SignupView.as_view(),name='signup'),
    path(route='me/profile/',view=views.UpdateProfileView.as_view(),name='update'),

    # Posts
    path( route='<str:username>/',view=views.UserDetailView.as_view(),name='detail')
]

templates/commun/footer.html
<!-- Contenido del footer de la web -->
<!-- se abre en header.html-->

<!--SCRIPT--INICIO------------------------------>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!--SCRIPT--FIN--------------------------------->
</body>
</html>

templates/commun/header.html
<!-- Contenido de cabecera de la web -->
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="App/assets/favicon.ico" />
    <!-- Bootstrap CSS: https://getbootstrap.com/docs/5.0/getting-started/introduction/ -->
    <link rel="stylesheet" href="{% static '/css/bootstrap/css/bootstrap.css' %}" />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="{% static '/css/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Animate CSS: https://animate.style/ -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <!-- Font awesome: https://fontawesome.com/v3/get-started/ -->
    <link rel="stylesheet" href="{% static '/css/fontawesome/css/all.min.css'%}"/>
    <link rel="stylesheet" href="{% static '/css/styles.css' %}"  />
    
    <title>{% if title %} {{title}} | Proyecto Python {% else %} Proyecto Python {% endif%}</title>
</head>
<body>
    {% include "commun/nav.html" %}

    
    <!-- Se cierra en fotter.html -->

templates/commun/nav-footer.html
<h1>nav footer</h1>

templates/commun/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">
        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "img/logo-icon.png" %}" height="45" class="d-inline-block align-top"/>
        </a>
        <div class="collapse navbar-collapse">
            
            <ul class="navbar-nav mr-auto">
                {% if request.user.profile %} 
                <li class="nav-item">
                    
                    
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" class="d-inline-block align-center nav-avatar"/>
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" class="d-inline-block align-center nav-avatar"/>
                        {% endif %}
                    </a>
                    

                        
                       
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-info btn-sm" role="button" data-bs-toggle="button" href="{% url 'users:logout' %}" ><i class="fas fa-plus"></i> Crear Post</a>                        
                    </a>
                </li>
                {% if request.user %}
                <li class="nav-item">
                    <a class="btn btn-outline-info btn-sm" href="{% url 'users:logout' %}" role="button"> <i class="fa-solid fa-arrow-right-from-bracket"></i> Salir</a>
                </li>
                {% else%}
                <li class="nav-item">
                <a class="btn btn-outline-infobtn-sm" href="{% url "users:signup" %}" role="button">
                    <img src="{% static 'img/default-profile.png' %}" height="50" class="d-inline-block align-top rounded-circle"/> Invitado

                </a>
            </li>
            {% endif %}
            {% else %}
            <li class="nav-item">
                <a class="btn btn-outline-info btn-sm" role="button" data-bs-toggle="button" href="{% url 'users:signup' %}" ><i class="fas fa-plus"></i> Registrarse</a>                        
                    </a>
            </li>
                    {% endif %}
            </ul>
            
        </div>
    </div>
</nav>