Project/urls.py
""" modulo de URLS general del proyecto """
#bibliografia ----------------------------------------------------
# https://github.com/django/django
# https://docs.djangoproject.com/en/4.0
#importaciones ---------------------------------------------------
#django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
#Views
from posts import views as posts_views
from users import views as users_views

#urls ---------------------------------------------------------------------------
urlpatterns = [
    #url para acceder a admin: ejem: http://127.0.0.1:8000/admin/
    path("admin/", admin.site.urls),#user:administrador; pass:Quieroentrar-77
    #urls apps -------------------------
    path('', include(('posts.urls', 'posts'), namespace='posts')),#include para incluir la lista de urls de post
    path('users/', include(('users.urls', 'users'), namespace='users')),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#archivos estáticos, le suma una url 

posts/urls.py
""" Post de URLS """
#code ---------------------------------------------------------------------------
# Django
from django.urls import path, include
# Views
from posts import views

#urls ---------------------------------------------------------------------------
urlpatterns = [
    #urls apps -------------------------
    path(route='', view=views.PostsFeedView.as_view(), name='feed'),
    path(route='posts/new/', view=views.CreatePostView.as_view(), name='create'),
    path(route='posts/<int:pk>/', view=views.PostDetailView.as_view(), name='detail') 
]

users/urls.py
"""Users URLs"""
# importaciones ------------------------------------------------------
# Django
from django.urls import path
# View
from users import views

# urls -------------------------------------------------------------------
urlpatterns = [
    # Management
    path(route='login/',view=views.LoginView.as_view(),name='login'),
    path(route='logout/',view=views.LogoutView.as_view(),name='logout'),
    path(route='signup/',view=views.SignupView.as_view(),name='signup'),
    path(route='me/profile/',view=views.UpdateProfileView.as_view(),name='update'),

    # Posts
    path( route='<str:username>/',view=views.UserDetailView.as_view(),name='detail')
]

users/models.py
""" USER model """
"""NOTE:bibliografia:
    https://docs.djangoproject.com/en/dev/topics/auth/customizing/#extending-the-existing-user-model
    https://docs.djangoproject.com/en/4.0/ref/models/fields/
    https://docs.djangoproject.com/en/4.0/ref/contrib/admin/
    """
#importaciones ---------------------------------------------------------
#django
from django.db import models
from django.contrib.auth.models import User #heredamos de user de django
# Create your models here.
#Nos vasamos en el modelo de usuario de Django admin
class Profile(models.Model):#en vez de USER le llamamos Profile por perfil de usuario
    """Profile model 
    modelo Proxy que extiende la base de datos con otra información"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Usuario")
    #? on_delete: que hace si se borra el user->en este caso acturá como un SQL
    biography = models.TextField(blank=True, verbose_name="Biografía") 
    phone_number = models.CharField(max_length=20, blank=True, verbose_name="Teléfono")
    #? blank=True, que permite que se quede vacio
    website = models.URLField(max_length=200, blank=True, verbose_name="Web")
    picture = models.ImageField(upload_to='users/pictures',blank=True,null=True, verbose_name="Avatar")#!Necesario instalar pip install Pillow
    #upload_to: donde se guardarán las imágenes
    created = models.DateTimeField(auto_now_add=True, verbose_name="Creación")#fechas de creación 
    modified = models.DateTimeField(auto_now=True, verbose_name="Modificación")#fecha de modificación 
    
    def __str__(self): #representacion en string en admin
        return f"biography: {self.biography} - website: {self.website} - picture: {self.picture} - created: {self.created} - modified: {self.modified}" 

users/forms.py
"""User formularios"""
"""Bibliografia: 
    https://docs.djangoproject.com/en/4.0/topics/forms/
    https://docs.djangoproject.com/en/4.0/ref/forms/fields/
    https://docs.djangoproject.com/en/4.0/ref/forms/widgets/
    https://docs.djangoproject.com/en/4.0/ref/forms/validation/

"""
#importaciones ---------------------------------------------------------
# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile

#code ---------------------------------------------------------
class SignupForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=50, label="Nombre usuario")
    password = forms.CharField(max_length=70,widget=forms.PasswordInput(), label="Contraseña")
    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput(), label="Repite Contraseña") # widget para validar el password y para que no sea visible

    first_name = forms.CharField(min_length=2, max_length=50, label="Nombre")
    last_name = forms.CharField(min_length=2, max_length=50, label = "Apellidos")

    email = forms.CharField( min_length=6,max_length=70,widget=forms.EmailInput(), label="Email") #widget para que lo valide como mail

    def clean_username(self):
        """Username debe ser único"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()#exists(): si existe no debuelve un booleano
        if username_taken:#si existe el usuario valida y avisa
            raise forms.ValidationError('Este usuario ya existe')
        return username

    def clean(self):
        """Verificar el password """
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return data

    def save(self):
        """Crear un perfil, lo guarda"""
        data = self.cleaned_data
        data.pop('password_confirmation')#sacamos este valor porque no necesitamos guardarlos
        user = User.objects.create_user(**data)#mandamos todo el diccioneario
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users views"""
#importaciones ---------------------------------------------------------
# Django
import profile
from urllib import request
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.urls import reverse, reverse_lazy #reverse construye una url
from django.views.generic import DetailView, FormView, UpdateView

# Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile

# Forms
from users.forms import SignupForm


class UserDetailView(DetailView): #class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'users/detail.html'
    slug_field = 'username' #necesitamos un identificador para queryset
    slug_url_kwarg = 'username' #como lo llamamos del lado del as url
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):#kwargs son los keywords arguments que se pasan 
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object() #get_object se encarga de traer los datos
        context['posts'] = Post.objects.filter(profile=user).order_by('-created')
        return context


class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form): #para salvar los datos del formulario
        form.save()
        return super().form_valid(form)

class UpdateProfileView(UpdateView): #class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self): #sobreescribimos el método
        return self.request.user.profile

    def get_success_url(self): #sobreescribimos el método
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username}) #reverse construye una url


class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'
    #recuerda cambiar la redirección de login en Settings del proyecto:
    #https://docs.djangoproject.com/en/4.0/topics/auth/default/#module-django.contrib.auth.views


class LogoutView(auth_views.LogoutView):#class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    template_name = 'users/logged_out.html'

templates/users/base.html
{% extends "../parent.html" %} {% load static %} {% block contenidoQueCambia %}
<!--variables -->

<!-- html -->
    <div class="d-flex flex-column justify-content-center align-items-center">
        <div class="col-xs-12 col-md-8 col-lg-6 user-login-card" id="auth-container">
            <div class="user-logo"><img src="{% static "img/logo-icon.png" %}"></div>
            {% block containerUser %}
            <!-- contenido que cambia -->
            {% endblock%}
        </div>
    </div>

{% endblock %}

templates/users/detail.html
{% extends "../parent.html" %} {% load static %} {% block contenidoQueCambia %}

{% comment %} {% block head_content %}
{% block title %} Detalle | Proyecto Python{% endblock %}
{% endblock %} {% endcomment %}


    <div class="container">
        <div class="row user-head">
           

            <div class="col-sm-12 ">
                <div class="avatar">
                    <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle"/>
                </div>
                <div class="row" style="font-size: 1.2em">
                    <div class="col-12">
                    <h2 style="font-weight: 100;">
                        {{ user.username }}
                        {% if user == request.user %}
                            <a
                                href="{% url "users:update" %}"
                                class="ml-5 btn btn-sm btn-outline-info"
                            >
                                Editar Perfil
                            </a>
                        {% else %}
                            <a
                                href=""
                                class="ml-5 btn btn-sm btn-primary"
                            >
                                Follow
                            </a>
                        {% endif %}
                    </h2>
                </div>
                   <div class="col-12 user-data">
                    <div>
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div>
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div>
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                    
                </div><div class="col-12">
                    <p>{{ user.profile.biography }}</p>
                </div>
                   </div>
                   
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url "posts:detail" post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}{% load static %}{% block containerUser %}
<!--variables -->
{% comment %} {% block title %} Login | Proyecto Python{% endblock %} {% endcomment %}

<!-- html -->

    {% if form.errors %}
        <p class="alert alert-danger">
            Tu usuario o contraseña no son correctos.<br>
            Intentalo de nuevo.
        </p>
    {% endif%}

    <form method="POST" action="{% url "users:login" %}">
        <!-- usamos url users:login -->
        {% csrf_token %}<!-- crea un token único por sesión para evitar hackeos-->
        <div class="form-group">
            <label for="formFile" class="form-label">Nombre usuario:</label>
            <input class="form-control form-control-lg" type="text" placeholder="Username" name="username" />
            <div><i>Prueba con Manolito</i></div>
        </div>
        <div class="form-group">
            <label for="formFile" class="form-label">Contraseña</label>
            <input class="form-control form-control-lg" type="password" placeholder="Password" name="password" />
            <div><i>Prueba con Quieroentrar00</i></div>
        </div>
        <button class="btn btn-primary btn-lg" type="submit">Acceder</button>
    </form>
    <p class="mt-4">¿Aún no tienes una cuenta? <a href="{% url "users:signup" %}">Registrate aquí.</a></p>

{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}{% load static %}{% block containerUser %}
<!--variables -->
{% comment %} {% block title %} Login | Proyecto Python{% endblock %} {% endcomment %}

<!-- html -->



    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {% comment %} {{ form.as_p }} {% endcomment %}
        <div class="form-group">
            <label for="formFile" class="form-label">Nombre de Usuario:</label>
            <input class="form-control form-control-lg" type="text" placeholder="Nombre de Usuario" name="username" />
        </div>
        <div class="form-group">
            <label for="formFile" class="form-label">Contraseña:</label>
            <input class="form-control form-control-lg" type="password" placeholder="Contraseña" name="password" />
        </div>
        <div class="form-group">
            <label for="formFile" class="form-label">Repetir Contraseña:</label>
            <input class="form-control form-control-lg" type="password" placeholder="Repite Contraseña" name="password_confirmation" />
        </div>
        <div class="form-group">
            <label for="formFile" class="form-label">Nombre:</label>
            <input class="form-control form-control-lg" type="text" placeholder="Nombre" name="first_name" />
        </div>
        <div class="form-group">
            <label for="formFile" class="form-label">Apellido:</label>
            <input class="form-control form-control-lg" type="text" placeholder="Apellido" name="last_name" />
        </div>
        <div class="form-group">
            <label for="formFile" class="form-label">Email:</label>
            <input class="form-control form-control-lg" type="email" placeholder="email@email.em" name="email" />
        </div>
        
        
        <button class="btn btn-primary btn-lg" type="submit">Registrarse</button>
        

    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "users/base.html" %}{% load static %}{% block containerUser %}
<!--variables -->
{% comment %} {% block title %} Login | Proyecto Python{% endblock %} {% endcomment %}

<!-- html -->
<form
  action="{% url 'users:update' %}"
  method="POST"
  enctype="multipart/form-data"
>
  {% csrf_token %}

  <div class="media">
    {% if profile.picture %}
    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
    {% else%}
    <img
      src="{% static 'img/default-profile.png' %}"
      class="rounded-circle"
      height="50"
    />
    {% endif %}

    <div class="media-body">
      <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
      <p class="ml-4"><input type="file" name="picture" /></p>
    </div>
  </div>

  {% for error in form.picture.errors %}
  <div class="alert alert-danger"><b>Avatar: </b>{{ error }}</div>
  {% endfor %}

  <hr />
  <br />

  {# Website field #}
  <div class="form-group">
    <label>Website</label>
    <input
      class="form-control {% if form.website.errors %}is-invalid{% endif %}"
      type="text"
      name="website"
      placeholder="Website"
      value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
    />
    <div class="invalid-feedback">
      {% for error in form.website.errors %} {{ error }} {% endfor%}
    </div>
  </div>

  {# Biography field #}
  <div class="form-group">
    <label>Biografía</label>
    <textarea
      class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
      name="biography"
    >
{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
    <div class="invalid-feedback">
      {% for error in form.biography.errors %} {{ error }} {% endfor%}
    </div>
  </div>

  {# Phone number field #}
  <div class="form-group">
    <label>Número de teléfono</label>
    <input
      class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
      type="text"
      name="phone_number"
      placeholder="Phone number"
      value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
    />
    <div class="invalid-feedback">
      {% for error in form.phone_number.errors %} {{ error }} {% endfor%}
    </div>
  </div>

  <button type="submit" class="btn btn-primary btn-block mt-5">
    Actualizar información
  </button>
</form>

{% endblock %}